### ISSUE TITLE
Surface overlaps player image

### ISSUE THREAD

**Issue by GH-Syn** [GH-Syn/Odyssey#26]
![](https://raw.githubusercontent.com/JoshuaDRose/Odyssey/42ac9e251d4c3add8fbabe6a795bc1f133f80b6c/docs/git/issue_mapping_surace_level.png)
> Shrubbery and anything that's not on the base surface level in tmx will essentially overlap player when the player should be on the top level.

**Comment by JoshuaDRose** [comment]
## ⏳ **Update**
I've been working on this for at least a day now, haven't found a fix. The only thing that comes close to a fix is having to create a custom class that inherits pytmx to add surfaces / surface layers ordering as that is what is [recommended in the docs](https://github.com/bitcraft/pytmx#custom-image-loading).

> see release 42ac9e251d4c3add8fbabe6a795bc1f133f80b6c for the original issue.
